name: flutter_graphql_client
description: "A new Flutter project."
version: 0.0.1
homepage: https://github.com/planetmedia-australia/flutter-graphql-client.git


environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  graphql_flutter: ^5.1.2
  action_cable: ^1.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
